# Generated by Django 4.2.6 on 2023-10-15 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_min_price', models.CharField(max_length=100)),
                ('plan_max_price', models.CharField(max_length=100)),
                ('plan_min_percentage', models.CharField(max_length=100)),
                ('plan_max_percentage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_direct', models.CharField(max_length=100, null=True)),
                ('percent_level_1', models.CharField(max_length=100, null=True)),
                ('percent_level_2', models.CharField(max_length=100, null=True)),
                ('percent_level_3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100, null=True)),
                ('wallet_id', models.CharField(max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=100, null=True)),
                ('withdraw_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.CharField(max_length=100)),
                ('user_status', models.CharField(max_length=100)),
                ('user_profit', models.CharField(max_length=100)),
                ('user_referral_profit', models.CharField(max_length=100, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=100)),
                ('direct', models.ManyToManyField(blank=True, related_name='%(class)s_direct', to=settings.AUTH_USER_MODEL)),
                ('level_1', models.ManyToManyField(blank=True, related_name='%(class)s_level1', to=settings.AUTH_USER_MODEL)),
                ('level_2', models.ManyToManyField(blank=True, related_name='%(class)s_level2', to=settings.AUTH_USER_MODEL)),
                ('level_3', models.ManyToManyField(blank=True, related_name='%(class)s_level3', to=settings.AUTH_USER_MODEL)),
                ('referral_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.referraldetails')),
                ('referred_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_referred', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('transaction_amount', models.CharField(max_length=100)),
                ('transaction_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Addprofit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.plans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
