# Generated by Django 4.2.6 on 2023-10-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='plan_price',
        ),
    ]
