# Generated by Django 4.2.6 on 2023-10-14 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=100)),
                ('direct', models.ManyToManyField(blank=True, related_name='%(class)s_direct', to=settings.AUTH_USER_MODEL)),
                ('level_1', models.ManyToManyField(blank=True, related_name='%(class)s_level1', to=settings.AUTH_USER_MODEL)),
                ('level_2', models.ManyToManyField(blank=True, related_name='%(class)s_level2', to=settings.AUTH_USER_MODEL)),
                ('level_3', models.ManyToManyField(blank=True, related_name='%(class)s_level3', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
