# Generated by Django 4.2.6 on 2023-10-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_referred', to=settings.AUTH_USER_MODEL),
        ),
    ]
