# Generated by Django 4.2.6 on 2023-10-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_plan_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plan',
            name='days',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
