# Generated by Django 4.2.6 on 2023-10-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_referral_referral_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referral_user',
            new_name='referred_user',
        ),
    ]
