# Generated by Django 4.2.6 on 2023-10-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_referral_user_referral_referred_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='percent_direct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='percent_level_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='percent_level_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='percent_level_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_plan',
            name='user_referral_profit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
