# Generated by Django 4.2.6 on 2023-10-15 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_referral_percent_direct_referral_percent_level_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_direct', models.CharField(max_length=100, null=True)),
                ('percent_level_1', models.CharField(max_length=100, null=True)),
                ('percent_level_2', models.CharField(max_length=100, null=True)),
                ('percent_level_3', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='referral',
            name='percent_direct',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='percent_level_1',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='percent_level_2',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='percent_level_3',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.referraldetails'),
        ),
    ]
